### ISSUE TITLE
Selecting Type of server in parameters

### ISSUE THREAD

**Issue by sneakyx** [apricote/hcloud-upload-image#30]
Your script is very nice, but we couldn't upload a 32GB image and I saw that there is only the possibility to create an cx11-server (x86 version).
It would be very good if there is a possibility to select the server type manually (for example with a parameter like "--server-type CX22" ).

**Comment by apricote** [comment]
Added in 0.3.0. I also updated the default to `cx22` (40 GB root disk), so you should be good to go even without overriding the selection.
