### ISSUE TITLE
Local file instead of url

### ISSUE THREAD

**Issue by LouKordos** [apricote/hcloud-upload-image#45]
Hi, is there a way to specify a local file path which will then be copied over via scp for example? Because looking at the source Code, I think only urls are currently supported and my Image is private enough that I don't want it on a public url. Thanks!

**Comment by apricote** [comment]
> Hi, is there a way to specify a local file path which will then be copied over via scp for example?

Thats possible, though it would not use `scp` but instead do it in the Go code.

- **CLI**: If you use the CLI you can use [`hcloud-upload-image upload --image-path=`](https://github.com/apricote/hcloud-upload-image/blob/main/docs/cli/hcloud-upload-?image_upload.md#options) option.
- **Library**: If you use the library its possible by setting [`UploadOptions.ImageReader`](https://pkg.go.dev/github.com/apricote/hcloud-upload-image/hcloudimages#UploadOptions) instead image `ImageURL`.

> my Image is private enough that I don't want it on a public url

You can always use something like an S3 pre-signed URL with a limited lifetime, but it also works from a local file.
